version: "3.9"
services:
  authservice:
    build:
      context: ${AUTH_SERVICE_PATH}
      dockerfile: Dockerfile
    container_name: auth-service
    restart: always
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      
  schoolservice:
    build:
      context: ${SCHOOL_SERVICE_PATH}
      dockerfile: Dockerfile
    container_name: school-service
    restart: always
    ports:
      - "8081:8080"
    environment:
      PORT: 8080

  medicalservice:
    build:
      context: ${MEDICAL_SERVICE_PATH}
      dockerfile: Dockerfile
    container_name: medical-service
    restart: always
    ports:
      - "8082:8080"
    environment:
      PORT: 8080
